Ported the ProfiledPIDSubsystem from the wpilib java source to Python
robotpy/robotpy-commands-v2 pull request #49
Opened 2024-01-21 20:22 UTC by cwstryker

Used ChatGPT to get 80% of the job done.  This is the ProfiledPIDSubsystem only.  No new tests were added.  I verified functionality using a separate robot simulation project.

2024-01-21 21:11 UTC, virtuald requested changes
Mostly good, thanks

2024-01-21 21:11 UTC, virtuald commented on commands2/profiledpidsubsystem.py
> +class ProfiledPIDSubsystem(Subsystem):
Comments missing for class

2024-01-21 21:11 UTC, virtuald commented on commands2/profiledpidsubsystem.py
> +        self._m_controller = controller
Get rid of the `_m`

2024-01-21 21:11 UTC, virtuald commented on commands2/profiledpidsubsystem.py
> +    def get_controller(self) -> ProfiledPIDController:
`getController`

2024-01-21 21:11 UTC, virtuald commented on commands2/__init__.py
> +from .profiledpidsubsystem import ProfiledPIDSubsystem
This needs to be in `__all__`

2024-01-21 22:01 UTC, cwstryker commented on commands2/profiledpidsubsystem.py
> +class ProfiledPIDSubsystem(Subsystem):
Added a docstring.

2024-01-21 22:01 UTC, cwstryker commented on commands2/profiledpidsubsystem.py
> +        self._m_controller = controller
Done.

2024-01-21 22:01 UTC, cwstryker commented on commands2/profiledpidsubsystem.py
> +    def get_controller(self) -> ProfiledPIDController:
Done.

2024-01-21 22:01 UTC, cwstryker commented on commands2/__init__.py
> +from .profiledpidsubsystem import ProfiledPIDSubsystem
Done.

2024-01-22 04:01 UTC, cwstryker reviewed
I think I fixed all of the issues.

2024-01-22 04:41 UTC, cwstryker commented
I see that some of the checks are failing.  I think I understand the cause of the issue.  I will work on fixing it tomorrow.

2024-01-22 17:43 UTC, virtuald commented
Thanks, everything looks good.

There are multiple ProfiledPIDControllers (one for dimensionless, and one for radians), and even though they're effectively the same thing there are some C++ classes that require one or the other. If you have any experience with python's typing generics, any ideas you have to make this work with both types of ProfiledPIDControllers would be welcomed.

I posted some thoughts on a related issue at https://github.com/robotpy/robotpy-commands-v2/pull/40, but I'm still mulling it over. 

If you don't have any ideas or expertise in this, that's fine. I'll contemplate and merge/adjust this once #46 is finished, which hopefully will be soon.

2024-01-24 07:42 UTC, virtuald commented
I'm going to merge this without typing for now. I don't really like the union approach, and I'm too tired to think through the generic/typevar approach. We can add types back at a later date.

2024-01-24 07:55 UTC, merged