Extract common trigger binding logic
robotpy/robotpy-commands-v2 pull request #79
Opened 2024-12-24 01:05 UTC by KangarooKoala

Also use previous and current

Port of https://github.com/wpilibsuite/allwpilib/pull/7550, which was merged before I could open this PR.

2024-12-24 02:02 UTC, TheTripleV approved these changes

2024-12-24 02:10 UTC, TheTripleV requested changes

2024-12-24 02:10 UTC, TheTripleV commented on commands2/button/trigger.py
> +    def _add_binding(self, body: Callable[bool, bool, NoneType]) -> None:
```suggestion
    def _add_binding(self, body: Callable[[bool, bool], None]) -> None:
```

2024-12-24 03:13 UTC, KangarooKoala commented
Thanks for apotting that! It's been too long since I've played with Python. (Side note- that decorator trick is also really cool! It makes sense now that I've seen it, but I don't think I'd have ever thought of it myself- I probably would've ended up translating the code into a single expression)

2024-12-24 17:50 UTC, KangarooKoala commented
Weird- The `check-mypy` failure is the same that's on main\*, but the test failures are really weird, since `test_swervecontrollercommand` is failing from a lack of numpy, but I didn't touch any of that.

\*By the way, it looks like `check-mypy` is failing on the return type mismatch in `Command.fork()` (which was added in https://github.com/robotpy/robotpy-commands-v2/pull/71 when it hadn't actually been added to WPILib - see https://github.com/wpilibsuite/allwpilib/pull/7083 - and the WPILib PR went in a different direction after the robotpy-commands PR was merged) and on missing `joystick.getDirectionDegrees()` and `joystick.getDirectionRadians()`, which were deprecated in 2023 in https://github.com/wpilibsuite/allwpilib/pull/5319 in favor of a unit overload and were removed in https://github.com/wpilibsuite/allwpilib/pull/6569.

My impulse would be to remove `Command.fork()` and wait until the WPILib PR gets merged since it's quite likely the version of `fork()` that ends up in WPILib will be different from what's currently in robotpy-commands. However, I'm quite new to robotpy-commands and I don't know if there's other reasons to go a different route.

I'm not familiar with how Python units work (How does the pybind work with the C++ units classes?), but it looks like you can probably implement `CommandJoystick.getDirectionDegrees()` and `CommandJoystick().getDirectionRadians()` in terms of `self._hid.getDirection()`, but I'm not sure.

2024-12-24 18:07 UTC, virtuald commented
I'm not sure why I merged fork. I agree it should be removed.

Python will pass units to C++ as a float, in the unit that the function parameter is specified as. There is no mechanism to check units, but the name of the unit ends up in the `.pyi` typestub file for the function.

2024-12-24 18:26 UTC, KangarooKoala commented
Any ideas on the `dist/ci/test` failures? (Example log here: https://github.com/robotpy/robotpy-commands-v2/actions/runs/12476284136/job/34841958986?pr=79)
They seem to be failing because numpy is missing, but I don't get how in the world my PR could've affected that.

2024-12-30 02:13 UTC, KangarooKoala commented
> By the way, it looks like `check-mypy` is failing on the return type mismatch in `Command.fork()` (which was added in #71 when it hadn't actually been added to WPILib - see [wpilibsuite/allwpilib#7083](https://github.com/wpilibsuite/allwpilib/pull/7083) - and the WPILib PR went in a different direction after the robotpy-commands PR was merged)

Update on this- The upstream PR was just closed, so `Command.fork()` definitely doesn't need to exist.

2024-12-30 08:31 UTC, auscompgeek commented
> They seem to be failing because numpy is missing

Hmm. I think a recent change to WPILib means `wpimath.geometry.Rotation2d`'s constructor has a dependency on numpy now. That dependency is missing in the robotpy-wpimath package metadata.

2025-01-03 02:59 UTC, auscompgeek commented
Those bugs should now be fixed if you rebase onto main.

2025-01-03 05:17 UTC, KangarooKoala commented
My bad, I forgot to pull after applying @TheTripleV's suggested change so when I rebased I accidentally dropped that commit.

2025-04-28 01:14 UTC, KangarooKoala commented
Any update on this?

2025-12-10 05:26 UTC, merged